export enum SearchActionTypes {
  FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST',
  FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS',
  FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL',
  SET_FROM_INPUT_ERROR = 'SET_FROM_INPUT_ERROR',
  CLEAR_FROM_INPUT_ERROR = 'CLEAR_FROM_INPUT_ERROR',
  SET_TO_INPUT_ERROR = 'SET_TO_INPUT_ERROR',
  CLEAR_TO_INPUT_ERROR = 'CLEAR_TO_INPUT_ERROR',
}
